<?php

return [
    'institution' => [
        'logo_url' => env('SKPI_INSTITUTION_LOGO_URL', ''),
        'name' => env('SKPI_INSTITUTION_NAME', 'STIT Digital'),
        'address' => env('SKPI_INSTITUTION_ADDRESS', 'Jl. Contoh No. 1, Jakarta'),
        'email' => env('SKPI_INSTITUTION_EMAIL', 'info@stitdigital.ac.id'),
        'website' => env('SKPI_INSTITUTION_WEBSITE', 'stitdigital.ac.id'),
        'sk_pendirian' => env('SKPI_INSTITUTION_SK', 'No. 123/STI/2021'),
        'program_studi' => env('SKPI_INSTITUTION_PROGRAM', 'Teknik Informatika'),
        'jenis_pendidikan' => env('SKPI_INSTITUTION_JENIS', 'Perguruan Tinggi'),
        'level_kkni' => env('SKPI_INSTITUTION_KKNI', 'Level 6'),
        'persyaratan_penerimaan' => env('SKPI_INSTITUTION_PERSYARATAN', 'Lulus SMA/SMK'),
        'bahasa_pengantar' => env('SKPI_INSTITUTION_BAHASA', 'Bahasa Indonesia'),
        'sistem_penilaian' => env('SKPI_INSTITUTION_SISTEM', 'Skala 4.00'),
        'lama_studi' => env('SKPI_INSTITUTION_LAMA', '4 tahun'),
        'sk_pendirian_date' => env('SKPI_INSTITUTION_SK_DATE', '1 Juni 1992'),
        'sk_pendirian_date_en' => env('SKPI_INSTITUTION_SK_DATE_EN', 'June 1, 1992'),
        'name_en' => env('SKPI_INSTITUTION_NAME_EN', 'STIT Digital'),
        'program_studi_en' => env('SKPI_INSTITUTION_PROGRAM_EN', 'Study Program'),
        'jenis_pendidikan_en' => env('SKPI_INSTITUTION_JENIS_EN', 'Academic and Bachelor Degree'),
        'level_kkni_en' => env('SKPI_INSTITUTION_KKNI_EN', 'Level 6'),
        'persyaratan_penerimaan_en' => env('SKPI_INSTITUTION_PERSYARATAN_EN', 'Graduate from High School or a Similar Level of Education'),
        'bahasa_pengantar_en' => env('SKPI_INSTITUTION_BAHASA_EN', 'Indonesian'),
        'sistem_penilaian_en' => env('SKPI_INSTITUTION_SISTEM_EN', '1-4; A=4, AB=3.5, B=3, BC=2.5, C=2, D=1, E=0'),
        'lama_studi_en' => env('SKPI_INSTITUTION_LAMA_EN', '4 years'),
    ],
    'leader' => [
        'name' => env('SKPI_LEADER_NAME', 'Dr. Rektor STIT'),
        'title' => env('SKPI_LEADER_TITLE', 'Ketua STIT'),
        'nidn' => env('SKPI_LEADER_NIDN', '0000000000'),
        'signature_path' => env('SKPI_LEADER_SIGNATURE_PATH', ''),
        'issued_place' => env('SKPI_LEADER_ISSUED_PLACE', 'Jakarta'),
    ],
    'document' => [
        'issued_place' => env('SKPI_DOCUMENT_PLACE', 'Jakarta'),
        'opening_text_id' => env('SKPI_OPENING_TEXT_ID', 'Surat keterangan ini diterbitkan sebagai bagian dari dokumen resmi institusi.'),
        'opening_text_en' => env('SKPI_OPENING_TEXT_EN', 'This certificate is issued as part of the institution\'s official documentation.'),
        'learning_outcomes' => [
            'knowledge' => env('SKPI_DOC_KNOWLEDGE', 'Memiliki penguasaan lintas disiplin sesuai kurikulum.'),
            'skills' => env('SKPI_DOC_SKILLS', 'Mampu menjalankan tugas profesional dengan kualitas dan etika tinggi.'),
            'attitudes' => env('SKPI_DOC_ATTITUDES', 'Menunjukkan integritas, tanggung jawab, dan komunikasi yang efektif.'),
        ],
        'learning_outcomes_en' => [
            'knowledge' => env('SKPI_DOC_KNOWLEDGE_EN', 'Able to master interdisciplinary concepts in accordance with the curriculum.'),
            'skills' => env('SKPI_DOC_SKILLS_EN', 'Able to carry out professional duties with high quality and ethics.'),
            'attitudes' => env('SKPI_DOC_ATTITUDES_EN', 'Exhibits integrity, responsibility, and effective communication.'),
        ],
        'working_capability' => [],
        'special_attitude' => [],
        'kkni_text_id' => env('SKPI_KKNI_TEXT_ID', 'SKPI ini merujuk pada Kerangka Kualifikasi Nasional Indonesia.'),
        'kkni_text_en' => env('SKPI_KKNI_TEXT_EN', 'This SKPI refers to the Indonesian National Qualification Framework (KKNI).'),
        'degree_title_en' => env('SKPI_DOCUMENT_DEGREE_TITLE_EN', 'Bachelor in Education'),
    ],
];
